spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cliente_api
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  sql:
    init:
      mode: never  # Disable Spring Boot's SQL initialization since we use Docker init scripts

server:
  port: 8080

logging:
  level:
    com.neoapp.cliente_api: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
